"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import django_heroku
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cccoevp@#xmtvi02ty^5(+!0p7hz&rwc=4t(a5x)dc_1f$sx*t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    # DJANGO PRE-INSTALLED APPS
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_nyt.apps.DjangoNytConfig',
    'admin_honeypot',
    'django_heroku',
    'gunicorn',
    # USER APPS
    'book.apps.BookConfig',
    'user.apps.UserConfig',
    'blog.apps.BlogConfig',
    # CRISPY FORMS

    'crispy_forms',
    # RATINGS APP FOR BOOK
    'star_ratings',
    # CLEANUP APP (CLEANS DELETED IMAGES FROM MEDIA)
    'django_cleanup.apps.CleanupConfig',
    # MESSAGE SYSTEM
    'postman',
    # DJANGO APP
    'django.contrib.sites',
    # TAGS APP
    'taggit',
    # FRIENDSHIP APP (INCLUDES FOLLOW MECHANISM)
    'friendship',
    # HITCOUNT APP FOR BLOG POSTS AND  BOOKS
    'hitcount',
    # LANGUAGE FIELD FOR BOOK
    'languages',
    # FEEDBACK APP
    'tellme',
    # COMMENTS APP FOR WHOLE SITE
    'comment',
    # SEARCH FILTER FOR APPS
    'django_filters',
    # FORM RENDERER FOR MAIN SITE
    'bootstrap4',
    # T&C APP
    'termsandconditions',
    # QR CODE APP
    'qrcode',
    # MAINTAINANCE MODE APP
    'maintenance_mode',

    # TODO APP
    'todo',
    # SHOWS COUNTRIES FOR USER PROFILE
    'django_countries',

    # APP PERFORMANCE INDICATORS
    'debug_toolbar',

    # PINAX APPS
    "account",
    "bootstrapform",
    "pinax.templates",
    "pinax.invitations",
    "pinax.teams",
    "reversion",
    "pinax.calendars",
    'easy_thumbnails',
    'mptt',
    'sekizai',
    'sorl.thumbnail',

    # EDITORS
    'tinymce',

    # MEM CACHE APP
    'cachalot',
    'django_user_agents',
    
    "pinax.images",

    # TRACK USERS AND ANALYZERS
    'tracking_analyzer',
    'tracking',

    # API APPS
    'rest_framework.authtoken',
    'rest_framework',
    'djoser',
    
]

# AUTHENTICATION_BACKENDS = [
#     pinax.likes.auth_backends.CanLikeBackend,
# ]
GEOIP_PATH = os.path.join(BASE_DIR, 'geoip2')

MIDDLEWARE = [
    'tracking.middleware.BannedIPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tracking.middleware.VisitorTrackingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.onlinenowMiddelware.OnlineNowMiddleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware',
    'termsandconditions.middleware.TermsAndConditionsRedirectMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    "pinax.teams.middleware.TeamMiddleware",
    "account.middleware.LocaleMiddleware",
    "account.middleware.TimezoneMiddleware",
    'django_user_agents.middleware.UserAgentMiddleware',
    'tracking.middleware.VisitorCleanUpMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'maintenance_mode.context_processors.maintenance_mode',
                "sekizai.context_processors.sekizai",
                "account.context_processors.account",
            ],
        },
    },
]
WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


#   DJANGO SETTINGS MANUAL


#STATIC SETTINGS
STATIC_URL = '/static/'
STATIC_ROOT = 'static/'

#MEDIA
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

#CRISPY FORMS SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap4'

#REDIRECT SETTINGS
LOGIN_URL = 'user_login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

#DJANGO MAIL SETTINGS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER='zoroknight000@gmail.com'
EMAIL_HOST_PASSWORD='N@gamani1999'
DEFAULT_FROM_EMAIL = "Flipin <Team@Flipin>"


#POSTMAN MESSAGES SETTINGS
POSTMAN_AUTO_MODERATE_AS =True


#TAGGIT APP
TAGGIT_CASE_INSENSITIVE = True

#Reidrect site id for postman and comments app change it if you add new site
SITE_ID = 1

#Book View settings


PROFILE_APP_NAME = 'user'
PROFILE_MODEL_NAME = 'Profile'


# DJANGO FILTER SETTINGS 

FILTERS_EMPTY_CHOICE_LABEL=''
def FILTERS_VERBOSE_LOOKUPS():
    from django_filters.conf import DEFAULTS

    verbose_lookups = DEFAULTS['VERBOSE_LOOKUPS'].copy()
    verbose_lookups.update({
    'exact': '',
    'iexact': '',
    'contains': '',
    'icontains': '',
    })
    return verbose_lookups
# DJANGO FILTER SETTINGS  ENDS HERE


# MAINTAINANCE MODE SETTINGS STARTS HERE
# Run python manage.py 
# maintenance_mode <on|off>
MAINTENANCE_MODE = None
MAINTENANCE_MODE_TEMPLATE='user/503.html'
MAINTENANCE_MODE_IGNORE_ADMIN_SITE = False
MAINTENANCE_MODE_RETRY_AFTER = 3600 # 1 hour

# MAINTAINANCE MODE SETTINGS END HERE

INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]


# TINY MCE SETTINGS STARTS HERE
TINYMCE_INCLUDE_JQUERY=True
TINYMCE_SPELLCHECKER=True
# TINY MCE SETTINGS ENDS HERE


# CACHEALOT SETTINGS STARTS HERE
CACHALOT_ENABLED=True
# CACHEALOT SETTINGS ENDS HERE

# DEBUG TOOLBAR SETTINGS STARTS HERE
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
    'cachalot.panels.CachalotPanel',
]
# DEBUG TOOLBAR SETTINGS ENDS HERE
# TRACK ANALYZER SETTINGS STARTS HERE
# db files : https://www.maxmind.com/en/geoip2-city
    # username:nagavarapradeepyendluri@gmail.com
    # password:08ar1a0424

GEOIP_PATH= os.path.join(BASE_DIR, 'geo')
# TRACK ANALYZER SETTINGS ENDS HERE

# DJANGO-TRACK APP SETTINGS STARTS HERE
TRACKING_USE_GEOIP=True
# DJANGO-TRACK APP SETTINGS ENDS HERE

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'PAGE_SIZE' : 12,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.IsAdminUser',
    ]
}
django_heroku.settings(locals())
