# Generated by Django 3.0.8 on 2020-07-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_explicitreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_author',
        ),
    ]
